# broker/mosquitto.conf
persistence true
persistence_location /mosquitto/data/

# dev-only: no auth
allow_anonymous true

# listen on TCP 1883
listener 1883 0.0.0.0

# (optional) websockets on 9001
# listener 9001 0.0.0.0
# protocol websockets
