version: '3'

services:
  data-db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'energy_data_db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3309:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      demo_net:
        ipv4_address: 172.30.2.3

  communication-backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8077:8082"
    environment:
      - DB_IP=data-db
      - DB_PORT=3306
      - DB_DBNAME=energy_data_db
      - DB_USER=root
      - DB_PASSWORD=root
    networks:
      demo_net:
        ipv4_address: 172.30.2.2

volumes:
  my-db:

networks:
  demo_net:
    external: true
