upstream backend-users{
    server ${BACKENDUSERS}:8080       max_fails=3 fail_timeout=240s;
}

upstream backend-devices{
    server ${BACKENDDEVICES}:8081     max_fails=3 fail_timeout=240s;
}

upstream backend-communications{
    server ${BACKENDCOMMUNICATIONS}:8082     max_fails=3 fail_timeout=240s;
}

upstream backend-chat{
    server ${BACKENDCHAT}:8083     max_fails=3 fail_timeout=240s;
}

server {

    listen  3000;
    server_name  localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $$uri /index.html;
    }

     location /spring-demo {
         proxy_pass http://backend-users;
    }

    location /springg-demo {
         proxy_pass http://backend-devices;
    }

    location /springgg-demo {
         proxy_pass http://backend-communications;
    }

    location /springggg-demo {
             proxy_pass http://backend-chat;
        }
}
